#!/usr/bin/env python3
"""writing to strings"""
import uuid
import redis
from typing import Union


class Cache:
    """creates the cache class"""
    def __init__(self):
        """initialize the redis instance"""
        self._redis = redis.Redis()
        self._redis.flushdb

    def store(self, data: Union[str, int, bytes, float]) -> str:
        """returns a string"""
        random_id = str(uuid.uuid4())
        self._redis.set(random_id, data.decode('utf-8'))
        return random_id
